### ISSUE TITLE
.gitignore Not working

### ISSUE THREAD

**Issue by HornOfSaltff** [RutgersGRID/VPVA-Prototype#1]
The .gitignore does not ignore certain files that it is supposed to ignore. This means that stuff in the unity project library is updated each time for every update/commit. This can be a problem when the files in the library get messed up. When you push a library with messed up files and then pull the project will want to start up in same mode. The fix here is to correct the .gitignore file.

**Comment by rianders** [comment]
Once items are added then a .gitnore is in place the committed files still remain.
________________________________
From: Eric ***@***.***>
Sent: Friday, February 10, 2023 9:40:05 AM
To: RutgersGRID/VPVA-Prototype ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RutgersGRID/VPVA-Prototype] .gitignore Not working (Issue #1)


The .gitignore does not ignore certain files that it is supposed to ignore. This means that stuff in the unity project library is updated each time for every update/commit. This can be a problem when the files in the library get messed up. When you push a library with messed up files and then pull the project will want to start up in same mode. The fix here is to correct the .gitignore file.
